// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMTool.Database;

#nullable disable

namespace PIMTool.Migrations
{
    [DbContext(typeof(PimContext))]
    [Migration("20231210023637_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Employee", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("Visa")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            BirthDate = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ly",
                            LastName = "Ngô",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 2m,
                            BirthDate = new DateTime(2002, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linh",
                            LastName = "Nguyễn",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 3m,
                            BirthDate = new DateTime(1994, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lan",
                            LastName = "Trần",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 4m,
                            BirthDate = new DateTime(1996, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Duy",
                            LastName = "Hoàng",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 5m,
                            BirthDate = new DateTime(1997, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Huy",
                            LastName = "Phan",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 6m,
                            BirthDate = new DateTime(2000, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Minh",
                            LastName = "Doãn",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 7m,
                            BirthDate = new DateTime(2001, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Quang",
                            LastName = "Tô",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 8m,
                            BirthDate = new DateTime(1999, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Trường",
                            LastName = "Phạm",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 9m,
                            BirthDate = new DateTime(1998, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tiến",
                            LastName = "Vũ",
                            Version = 0m,
                            Visa = "VN"
                        },
                        new
                        {
                            Id = 10m,
                            BirthDate = new DateTime(2004, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thịnh",
                            LastName = "Đinh",
                            Version = 0m,
                            Visa = "VN"
                        });
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Group", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<decimal>("GroupLeaderId")
                        .HasColumnType("numeric(19,0)");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupLeaderId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            GroupLeaderId = 9m,
                            Version = 0m
                        },
                        new
                        {
                            Id = 2m,
                            GroupLeaderId = 8m,
                            Version = 0m
                        },
                        new
                        {
                            Id = 3m,
                            GroupLeaderId = 7m,
                            Version = 0m
                        },
                        new
                        {
                            Id = 4m,
                            GroupLeaderId = 6m,
                            Version = 0m
                        },
                        new
                        {
                            Id = 5m,
                            GroupLeaderId = 5m,
                            Version = 0m
                        });
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Project", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(19,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ProjectNumber")
                        .HasColumnType("numeric(4,0)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.ProjectEmployee", b =>
                {
                    b.Property<decimal>("ProjectId")
                        .HasColumnType("numeric(19,0)");

                    b.Property<decimal>("EmployeeId")
                        .HasColumnType("numeric(19,0)");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectEmployees");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Group", b =>
                {
                    b.HasOne("PIMTool.Core.Domain.Entities.Employee", "GroupLeader")
                        .WithMany("Groups")
                        .HasForeignKey("GroupLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupLeader");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("PIMTool.Core.Domain.Entities.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.ProjectEmployee", b =>
                {
                    b.HasOne("PIMTool.Core.Domain.Entities.Employee", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMTool.Core.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("PIMTool.Core.Domain.Entities.Group", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
